version: '3'
services:
  app:
    restart: always
    build: . 
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "5000"
    environment:
      - APP_VERSION=1.0.0
    env_file:
      - ./env_config
    networks:
      - nodeapp-network 
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - nodeapp-network 
    ports:
      - 27017:27017
networks:
  nodeapp-network:
    driver: bridge